// Generated by CoffeeScript 1.6.1
(function() {
  var drawPig, incidence, maxRotation, pig, random, updatePig,
    _this = this;

  updatePig = function(maxRotation) {
    var rotation;
    if (random(0, incidence) === 1) {
      return;
    }
    rotation = random(0, maxRotation * 2) - maxRotation;
    drawPig(rotation);
  };

  drawPig = function(rotateAmount) {
    var rotation;
    rotation = rotateAmount;
    pig.style.webkitTransform = "rotate(" + rotation + "deg)";
  };

  random = function(min, max) {
    return Math.floor((Math.random() * max) + min);
  };

  pig = $("#pig")[0];

  maxRotation = 10;

  incidence = 10;

  setInterval(function() {
    return updatePig(10);
  }, 3000);

}).call(this);
